server:
  port: 8080
  origin: ${ORIGIN:*}
spring:
  application:
    name: cargame
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://retoweb:retoweb123@clusterreto.ikmfg.mongodb.net/cargame?retryWrites=true&w=majority}
  rabbitmq:
    addresses: ${BUS_URI:amqps://misgylcb:F3gHPgLKSE0L2WlfiqoSSPFX3858uEhq@chimpanzee.rmq.cloudamqp.com/misgylcb}
